### ISSUE TITLE
Cleanup Android Lint errors

### ISSUE THREAD

**Issue by msgilligan** [rivetz/SampleApp#5]
From the Gradle output:

     > Task :app:lint
    Ran lint on variant release: 15 issues found 
    Ran lint on variant debug: 15 issues found
    Wrote HTML report to file:///xxx/yyy/Rivetz/git/SampleApp/app/build/reports/lint-results.html
    Wrote XML report to file:///xxx/yyy/Rivetz/git/SampleApp/app/build/reports/lint-results.xml

If you open the file `app/build/reports/lint-results.html` you can see more detailed information about the errors.

**Comment by msgilligan** [comment]
@jdbgit This is not the highest priority, but those errors should be cleaned up at some point.

**Comment by jdbgit** [comment]
No longer applicable as the app has changed entirely...
