### ISSUE TITLE
When RivetzJ 0.7.2 is released update to it and remove reference to snapshots repo

### ISSUE THREAD

**Issue by msgilligan** [rivetz/SampleApp#9]

**Comment by jdbgit** [comment]
Is there a notification posted when a new update is available?

**Comment by msgilligan** [comment]
Currently I announce releases internally (on Rivetz.Chat) and there is a section on announcements in the `doc/release-process.adoc` file in the RivetzJ repository. We could add a step to make announcements on other channels and perhaps even automate the process in the future.

**Comment by msgilligan** [comment]
See PR #10
